### ISSUE TITLE
How to connec to the the pod?

### ISSUE THREAD

**Issue by ghost** [rosskukulinski/nginx-kubernetes-reload#1]
Hi, I have a setup inspired by this configuration but I am not able to access the pod(I am on GKE). When I run `docker exec -ti XXXX sh` I will get:
`rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"sh\": executable file not found in $PATH`

I tried various programs but I get the same result. Is it the issue with the `ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]` ? Is there a way around it?

**Comment by rosskukulinski** [comment]
@ivanjaros Sorry I missed this issue, I wasn't watching the repo!

The base image for this is nginx-apline, which has `bash` as the shell of choice.

`kubectl -n kukulinski-com exec -ti gateway-2089280900-3gxn3 /bin/bash` worked for me.

**Comment by ghost** [comment]
Thanks, I haven't worked with it for a while now though :)
